### ISSUE TITLE
Add dashboard widgets to mobile

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/files-clients#17]
Check
- API
  - retrieve items: https://github.com/nextcloud/server/blob/51add75e515e16e9ca259b46f0e82621cfa280fc/apps/dashboard/lib/Controller/DashboardApiController.php#L69
  - how to list available widgets, with name, icon, etc
  - format of entries?
  - are all apis accessible from clients (via OCS)
  - documentation of it
  - @eneiluj can you shed some light here? :)
- Mobile
  - when adding widget show list of possible widget
  - retrieve items every 60s (with eTag, so transferred data is smaller)
  - possible to have interactive entries (like actions in notifications)

- [ ] Android https://github.com/nextcloud/android/issues/10629
- [ ] iOS https://github.com/nextcloud/ios/issues/2122
- [ ] Server https://github.com/nextcloud/server/issues/31322

**Comment by thisIsTheFoxe** [comment]
### iOS
- available iOS 13+
- have to be built using SiwftUI
- widget size family and kind have to be defined at design time and cannot be changed at runtime!
- widget configuration is powered by SiriKit Intents which can be fetched dynamically (e.g. Stocks.app)
  - can provide e.g. a list of items for the user to select
- widget reloads are **budgeted** and depend on user interaction with the widget (same goes for smart stacks)
  - widgets can be reloaded for free when the app is in foreground
  - widgets displaying dynamic data have to schedule how long it can wait until it should be updated (typically every ~30 min. or  ~40 times/day) [<sup>docs</sup>](https://developer.apple.com/documentation/widgetkit/keeping-a-widget-up-to-date)

A widget _kind_ shares a common name and description and can only have one entry per size family (but obviously the user can add the same widget multiple times and have different configurations for each). 
I think it makes sense to use a Intent configuration here and only have 'one widget kind' available and the user can then select which app content they want it to display. Also, since most dashboard widgets have a similar web UI afaik, it should be a pretty uniform experience.

**Comment by tobiasKaminsky** [comment]
Android: 
https://developer.android.com/guide/topics/appwidgets

- can be dynamic
- update interval can be chosen

**Comment by eneiluj** [comment]
The dashboard API is briefly described there: https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/dashboard.html#dashboard-api-for-clients

This API is OCS-only, yes.

Basically you can't really get a list of all the widgets but only those who implement the `IAPIWidget` interface.
In the API request, you can specify the date of the last entry you already got for each widget to make sure you get only new entries/items.
The result is a JSON object indexed by the widget ID and which contains lists of items. Each item is an object with those keys:
* subtitle
* title
* link
* iconUrl
* sinceId (date of the item that can be used in the next request)

There is no way to get information on the widgets right now. We could add that to the API as separate endpoint which would return a list of enabled widgets and their attributes like the icon, title and id. Warning, the icon is actually just a class. It would require some changes to be able to provide the icon content or a link in such API endpoint.

**Comment by jancborchardt** [comment]
Design-wise on mobile, it’s probably best if we use a tab bar for the different widgets, and then a simple list view below for the contents of the widget? (It seems though that Material Design 3 e.g. doesn’t have the tab bar anymore, but then we could do it via cards, so it looks like the Dashboard on web.)

For Desktop it’s probably best to integrate with native desktop widget mechanisms?

**Comment by tobiasKaminsky** [comment]
I assumed it will be one dashboard-entry per widget, so e.g. you then have a widget for Talk and one for activity.
Upon adding this to homescreen user can select which dashboard-source should be used.

**Comment by tobiasKaminsky** [comment]
@PVince81 please schedule server side part, as written by Julien.

**Comment by PVince81** [comment]
tech ticket raised here: https://github.com/nextcloud/server/issues/31322
